import os
import json
import logging
import requests
import csv
from flask import Flask, render_template, request, jsonify
from dotenv import load_dotenv
from groq import Groq
from amadeus import Client, ResponseError
import openrouteservice
import razorpay

# Load environment variables
load_dotenv(override=True)

app = Flask(__name__)
app.config['SECRET_KEY'] = os.urandom(24)

# --- Auto copy images generated by AI Assistant ---
import shutil, glob
os.makedirs('static/img', exist_ok=True)
hero_imgs = glob.glob(r'C:\Users\Uma Mahesh\.gemini\antigravity\brain\3897aae1-5835-4b88-a969-1dc98b42bf22\hero_travel_background_*.png')
bot_imgs = glob.glob(r'C:\Users\Uma Mahesh\.gemini\antigravity\brain\3897aae1-5835-4b88-a969-1dc98b42bf22\ai_bot_icon_*.png')
if hero_imgs:
    shutil.copy(hero_imgs[-1], 'static/img/hero.png')
if bot_imgs:
    shutil.copy(bot_imgs[-1], 'static/img/bot.png')
# ------------------------------------------------

# Configure logging
logging.basicConfig(level=logging.INFO)

@app.context_processor
def inject_supabase():
    return dict(
        supabase_url=os.getenv("SUPABASE_URL", ""),
        supabase_key=os.getenv("SUPABASE_KEY", "")
    )

# API Keys
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")
FOURSQUARE_API_KEY = os.getenv("FOURSQUARE_API_KEY")
OPENTRIPMAP_API_KEY = os.getenv("OPENTRIPMAP_API_KEY")
AMADEUS_CLIENT_ID = os.getenv("AMADEUS_CLIENT_ID")
AMADEUS_CLIENT_SECRET = os.getenv("AMADEUS_CLIENT_SECRET")
OPENROUTESERVICE_API_KEY = os.getenv("OPENROUTESERVICE_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")

# Initialize Razorpay Client
if RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET:
    razorpay_client = razorpay.Client(auth=(RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET))
else:
    razorpay_client = None
    logging.warning("No Razorpay credentials found. Payments will not work.")

# Initialize Groq client (Fallback)
if GROQ_API_KEY:
    groq_client = Groq(api_key=GROQ_API_KEY)
else:
    groq_client = None
    logging.warning("No GROQ_API_KEY found.")

def get_ai_response(messages, temp=0.7):
    # Try OpenRouter First
    if OPENROUTER_API_KEY:
        try:
            url = "https://openrouter.ai/api/v1/chat/completions"
            headers = {
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "HTTP-Referer": "http://localhost:5000",
                "X-Title": "Eureka AI Trip Planner",
                "Content-Type": "application/json"
            }
            # Using a fast, high quality model
            payload = {
                "model": "google/gemini-2.0-flash-001",
                "messages": messages,
                "temperature": temp
            }
            r = requests.post(url, headers=headers, json=payload, timeout=30)
            if r.status_code == 200:
                result = r.json()
                return result['choices'][0]['message']['content']
        except Exception as e:
            logging.error(f"OpenRouter Error: {e}")

    # Fallback to Groq
    if groq_client:
        try:
            response = groq_client.chat.completions.create(
                messages=messages,
                model="llama-3.3-70b-versatile",
                temperature=temp,
            )
            return response.choices[0].message.content
        except Exception as e:
            logging.error(f"Groq Fallback Error: {e}")
            
    return None

# Initialize Amadeus client
if AMADEUS_CLIENT_ID and AMADEUS_CLIENT_SECRET:
    amadeus = Client(client_id=AMADEUS_CLIENT_ID, client_secret=AMADEUS_CLIENT_SECRET)
else:
    amadeus = None
    logging.warning("No Amadeus credentials found.")

# Initialize OpenRouteService client
if OPENROUTESERVICE_API_KEY:
    ors_client = openrouteservice.Client(key=OPENROUTESERVICE_API_KEY)
else:
    ors_client = None
    logging.warning("No OpenRouteService API key found.")

@app.context_processor
def inject_supabase():
    return dict(
        supabase_url=os.getenv("SUPABASE_URL"),
        supabase_key=os.getenv("SUPABASE_KEY")
    )

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')

@app.route('/planner')
def planner():
    return render_template('planner.html')

@app.route('/results')
def results():
    return render_template('results.html')

@app.route('/connect')
def connect():
    return render_template('connect.html')

@app.route('/map')
def map_page():
    return render_template('map.html')

@app.route('/pricing')
def pricing():
    return render_template('pricing.html')

@app.route('/api/create_razorpay_order', methods=['POST'])
def create_razorpay_order():
    if not razorpay_client:
        return jsonify({'error': 'Payment gateway not configured on server (Missing Keys)'}), 500
        
    try:
        data = request.get_json(silent=True) or {}
        plan_price = 19900 # amount in PAISE (₹199)
        
        order_data = {
            'amount': plan_price,
            'currency': 'INR',
            'receipt': 'eureka_pro_upgrade',
            'payment_capture': 1
        }
        order = razorpay_client.order.create(data=order_data)
        
        return jsonify({
            'order_id': order['id'],
            'amount': order['amount'],
            'currency': order['currency'],
            'key': RAZORPAY_KEY_ID
        })
    except Exception as e:
        logging.error(f"Razorpay Order Error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/verify_payment', methods=['POST'])
def verify_payment():
    data = request.json
    try:
        # Verify the signature
        params_dict = {
            'razorpay_order_id': data['razorpay_order_id'],
            'razorpay_payment_id': data['razorpay_payment_id'],
            'razorpay_signature': data['razorpay_signature']
        }
        razorpay_client.utility.verify_payment_signature(params_dict)
        
        # Payment verified securely
        # TODO: Here we would trigger a Supabase DB UPDATE to set user_profiles.plan_type = 'pro'
        
        return jsonify({'status': 'success', 'message': 'Payment verified successfully! Welcome to Eureka Pro!'})
    except razorpay.errors.SignatureVerificationError:
        return jsonify({'status': 'failure', 'message': 'Payment signature verification failed. Possible tampering.'}), 400
    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)}), 500

@app.route('/api/create_hotel_booking', methods=['POST'])
def create_hotel_booking():
    if not razorpay_client:
        return jsonify({'error': 'Payment gateway not configured on server (Missing Keys)'}), 500
        
    try:
        data = request.json
        # Convert supplied price to proper integer amount in paise (default to 2000 INR if invalid)
        try:
            price_in_inr = int(float(str(data.get('price', 2000)).replace(',', '')))
        except ValueError:
            price_in_inr = 2000
            
        hotel_name = data.get('hotel_name', 'Eureka Accommodations')
        
        order_data = {
            'amount': price_in_inr * 100, # amount in PAISE
            'currency': 'INR',
            'receipt': 'booking_' + os.urandom(3).hex(),
            'payment_capture': 1
        }
        order = razorpay_client.order.create(data=order_data)
        
        return jsonify({
            'order_id': order['id'],
            'amount': order['amount'],
            'currency': order['currency'],
            'key': RAZORPAY_KEY_ID,
            'hotel_name': hotel_name
        })
    except Exception as e:
        logging.error(f"Razorpay Hotel Order Error: {e}")
        return jsonify({'error': str(e)}), 500

@app.route('/api/verify_hotel_booking', methods=['POST'])
def verify_hotel_booking():
    data = request.json
    try:
        params_dict = {
            'razorpay_order_id': data['razorpay_order_id'],
            'razorpay_payment_id': data['razorpay_payment_id'],
            'razorpay_signature': data['razorpay_signature']
        }
        razorpay_client.utility.verify_payment_signature(params_dict)
        return jsonify({'status': 'success', 'receipt_id': data['razorpay_payment_id']})
    except razorpay.errors.SignatureVerificationError:
        return jsonify({'status': 'failure', 'message': 'Signature mismatch!'}), 400
    except Exception as e:
        return jsonify({'status': 'error', 'message': str(e)}), 500

@app.route('/chat')
def chat():
    return render_template('chat.html')

@app.route('/auth')
def auth():
    return render_template('auth.html')

def normalize_city(city_name):
    if not city_name: return ""
    c = city_name.lower().strip()
    if c in ["bengaluru", "bangalore", "blr", "sbc", "yeshwantpur", "ypr"]: return "bangalore"
    if c in ["mysuru", "mysore", "mysure", "mys"]: return "mysore"
    if c in ["mangaluru", "mangalore", "mlr", "maq", "majn"]: return "mangalore"
    if c in ["hubbali", "hubli", "hbl", "ubl"]: return "hubli"
    if c in ["belagavi", "belgaum", "bgm"]: return "belgaum"
    if c in ["shivamogga", "shimoga", "sme"]: return "shimoga"
    if c in ["kalaburagi", "gulbarga", "klbg", "gr"]: return "gulbarga"
    if c in ["chikkamagaluru", "chikmagalur", "cmgr"]: return "chikkamagaluru"
    if c in ["davangere", "davanagere", "dvg"]: return "davangere"
    return c

def get_train_route(source, destination):
    if not source or not destination:
        return None
    try:
        json_path = os.path.join(os.path.dirname(__file__), 'data', 'trains.json')
        if not os.path.exists(json_path):
            return None
        with open(json_path, 'r', encoding='utf-8') as f:
            trains = json.load(f)
            src_norm = normalize_city(source)
            dest_norm = normalize_city(destination)
            for t in trains:
                if normalize_city(t.get('source_city')) == src_norm and normalize_city(t.get('destination_city')) == dest_norm:
                    return t
    except Exception as e:
        logging.error(f"Error reading trains.json: {e}")
    return None

def get_local_hotels(destination, budget, days):
    try:
        # Better budget logic: Find ALL hotels in the city that fit under (budget / days)
        max_per_night = float(budget) / float(days) if float(days) > 0 else float(budget)
        
        csv_path = os.path.join(os.path.dirname(__file__), 'data', 'karnataka_hotels.csv')
        if not os.path.exists(csv_path):
            return None
            
        matches = []
        dest_norm = normalize_city(destination)
        with open(csv_path, mode='r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                if normalize_city(row['city']) == dest_norm:
                    price = float(row['price_min_inr'])
                    if price <= max_per_night * 1.5: # 50% buffer to show slightly better options if close
                        matches.append({
                            "name": row['name'],
                            "area": row['area'],
                            "price": price,
                            "rating": row['avg_rating'],
                            "type": row['type'],
                            "amenities": row['amenities']
                        })
        
        # Sort by price ascending to prioritize budget
        matches.sort(key=lambda x: x['price'])
        return matches[:5] if matches else None
    except Exception as e:
        logging.error(f"Error reading local CSV: {e}")
        return None

def get_local_food(destination):
    try:
        csv_path = os.path.join(os.path.dirname(__file__), 'data', 'city_local_food_combined.csv')
        if not os.path.exists(csv_path):
            return []
            
        matches = []
        dest_norm = normalize_city(destination)
        with open(csv_path, mode='r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                if normalize_city(row['city']) == dest_norm:
                    matches.append({
                        "dish_name": row['dish_name'],
                        "category": row['category'],
                        "description": row['description']
                    })
        return matches
    except Exception as e:
        logging.error(f"Error reading local food CSV: {e}")
        return []

def fetch_foursquare(destination, category):
    if not FOURSQUARE_API_KEY:
        return []
    headers = {
        "Accept": "application/json",
        "Authorization": FOURSQUARE_API_KEY
    }
    url = f"https://api.foursquare.com/v3/places/search?near={destination}&query={category}&limit=5"
    try:
        r = requests.get(url, headers=headers, timeout=5)
        if r.status_code == 200:
            results = r.json().get('results', [])
            return [res.get('name') for res in results]
    except Exception as e:
        logging.error(f"Foursquare Error: {e}")
    return []

def get_coordinates(destination):
    # Try OpenTripMap first
    if OPENTRIPMAP_API_KEY:
        url = f"https://api.opentripmap.com/0.1/en/places/geoname?name={destination}&apikey={OPENTRIPMAP_API_KEY}"
        try:
            r = requests.get(url, timeout=5)
            if r.status_code == 200:
                data = r.json()
                return data.get('lat'), data.get('lon')
        except Exception:
            pass
    
    # Fallback to OpenWeather Geocoding
    if WEATHER_API_KEY:
        url = f"http://api.openweathermap.org/geo/1.0/direct?q={destination}&limit=1&appid={WEATHER_API_KEY}"
        try:
            r = requests.get(url, timeout=5).json()
            if r:
                return r[0]['lat'], r[0]['lon']
        except Exception:
            pass
    return None, None

def fetch_opentripmap(lat, lon, category="interesting_places"):
    if not OPENTRIPMAP_API_KEY or lat is None or lon is None:
        return []
    url = f"https://api.opentripmap.com/0.1/en/places/radius?radius=5000&lon={lon}&lat={lat}&kinds={category}&format=json&limit=5&apikey={OPENTRIPMAP_API_KEY}"
    try:
        r = requests.get(url, timeout=5)
        if r.status_code == 200:
            return [place.get('name') for place in r.json() if place.get('name')]
    except Exception as e:
        logging.error(f"OpenTripMap Error: {e}")
    return []

def fetch_amadeus_hotels(city_code):
    if not amadeus:
        return []
    try:
        # Note: Amadeus requires city codes (e.g., DEL for Delhi).
        # We'll rely on the AI to provide the correct code or default to destination name for simplicity in this version.
        response = amadeus.reference_data.locations.hotels.by_city.get(cityCode=city_code)
        return [{"name": h['name'], "hotelId": h['hotelId']} for h in response.data[:5]]
    except ResponseError as error:
        logging.error(f"Amadeus Error: {error}")
    return []

@app.route('/api/plan_trip', methods=['POST'])
def plan_trip():
    data = request.json
    destination = data.get('destination')
    budget = data.get('budget')
    days = data.get('days')
    people = data.get('people')
    preferences = data.get('preferences', '')
    language = data.get('language', 'English')

    if not destination:
        return jsonify({"error": "Missing destination"}), 400

    # 1. Geocoding
    # Geocode Source if provided
    source = data.get('source')
    source_lat, source_lon = None, None
    if source:
        source_lat, source_lon = get_coordinates(source)

    lat, lon = get_coordinates(destination)

    real_attractions = fetch_opentripmap(lat, lon, "interesting_places") or ["Main tourist spots in " + destination]
    
    real_hotels_data = get_local_hotels(destination, budget, days)
    hotel_context = "STRICT: No affordable hotels found in dataset for this city. DO NOT INVENT HOTEL NAMES. Suggest staying with friends, using a public dormitory, or an overnight train if budget is too tight."
    if real_hotels_data:
        hotel_context = "REAL HOTELS FROM DATASET (ONLY USE THESE): " + ", ".join([f"{h['name']} in Area: {h['area']} (Price: ₹{h['price']}, Rating: {h['rating']}/5)" for h in real_hotels_data])

    # Ensure source is normalized or defaulted
    if not source:
        source = "Bangalore" # Default starting point for Karnataka trips if user omitted it
    
    # Render Train Travel (Local Dataset)
    real_train = get_train_route(source, destination)
    
    train_context = "No train found in dataset."
    if real_train:
        train_context = f"Train: {real_train['train_name']} (#{real_train['train_number']}), Price: ₹{real_train['price']}, Dep: {real_train['departure_time']}, Arr: {real_train['arrival_time']}"

    real_restaurants = fetch_foursquare(destination, "Restaurant") or ["Best local eateries in " + destination]

    # Culinary Dataset Integration
    real_food_data = get_local_food(destination)
    food_context = "No specific dishes in dataset. Suggest generic local Karnataka cuisine."
    if real_food_data:
        food_context = ", ".join([f"{f['dish_name']} ({f['category']}: {f['description']})" for f in real_food_data])

    # --- INTELLIGENT BUDGET PREDICTION LOGIC ---
    # Calculate Absolute Minimum Based on Real Data
    min_hotel = 0
    if real_hotels_data:
        min_hotel = min([h['price'] for h in real_hotels_data]) * (float(days) if float(days) > 0 else 1)
    
    min_transport = 0
    if real_train:
        min_transport = float(real_train['price']) * 2 # Round trip
    
    # Minimum for food and local travel (very low end)
    min_subsistence = 400 * (float(days) if float(days) > 0 else 1)
    
    abs_min_required = min_hotel + min_transport + min_subsistence
    user_budget_float = float(budget) if budget else 1000
    
    is_budget_low = user_budget_float < abs_min_required
    effective_budget = user_budget_float
    budget_instructions = f"User's Total Budget: STRICTLY ₹{user_budget_float} INR."
    
    if is_budget_low:
        effective_budget = abs_min_required + 500 # Add a small buffer for the predicted budget
        budget_instructions = f"CRITICAL: User's entered budget (₹{user_budget_float}) is TOO LOW for this trip. We have predicted a more realistic budget of ₹{effective_budget} INR based on actual hotel/train prices. PLEASE PLAN FOR ₹{effective_budget} INR AND EXPLAIN IN NOTES WHY IT WAS INCREASED."

    messages = [
        {"role": "system", "content": f"You are a professional travel planner API. You MUST return ONLY a valid, strict JSON object. All string values MUST be translated into {language}. Target budget is ₹{effective_budget} INR."},
        {"role": "user", "content": f"""
Plan a {days}-day trip to {destination}, Karnataka for {people} person.
{budget_instructions}

CRITICAL DATA FROM OUR DATASETS:
- Hotel Options (USE THESE PRICES): {hotel_context}
- Train Option (USE THIS PRICE): {train_context}
- Local Famous Dishes (MANDATORY TO MENTION): {food_context}

INSTRUCTIONS:
1. The `recommended_budget_inr` field MUST be exactly ₹{budget} or less. 
2. In `budget_analysis`, ensure Accommodation + Food + Travel + Activities = total budget. 
3. If the budget is low (e.g. ₹2,000 for 2 days), use the cheapest hotel from the dataset provided.
4. IMPORTANT: NEVER make up or hallucinate a hotel name. If `Hotel Options` context says 'No affordable hotels found', then do NOT include any hotels in the `hotels` array or `budget_analysis`. Instead, mention in `notes` that the budget is too low for hotels and suggest budget-saving alternatives like dormitories.
5. PROXIMITY PLANNING: Prioritize attractions and restaurants that are in the same or nearby 'Area' of the selected hotel to minimize travel time for the user.
6. Itinerary activities must be logically priced to fit the remainder.

STRICT JSON SCHEMA (Return ONLY raw JSON):
{{
  "destination": "{destination}",
  "destination_translated": "...",
  "lat": number,
  "lon": number,
  "budget_analysis": {{
    "recommended_budget_inr": {effective_budget},
    "estimated_accommodation_cost_inr": number,
    "estimated_food_cost_inr": number,
    "estimated_travel_cost_inr": number,
    "estimated_activities_cost_inr": number,
    "notes": "Advice on how to stay under the recommended budget in {language}"
  }},
  "itinerary": [
    {{
      "day": number,
      "theme": "...",
      "day_cost_inr": number,
      "activities": [
        {{ "name": "...", "lat": number, "lon": number, "cost_estimate_inr": number }}
      ]
    }}
  ],
  "hotels": [
    {{ "name": "Name from dataset", "area": "...", "price_per_night_inr": number, "rating": number, "lat": number, "lon": number, "reason": "Reason in {language}" }}
  ],
  "local_food": {json.dumps(real_food_data) if real_food_data else "[]"},
  "total_distance_km": number,
  "train_details": {json.dumps(real_train) if real_train else "null"}
}}
"""}
    ]
    
    result_text = get_ai_response(messages, temp=0.2)
    if not result_text:
        return jsonify({"error": "AI could not generate a response"}), 500
    
    try:
        # Strip potential markdown formatting
        if result_text.startswith('```'):
            import re
            result_text = re.sub(r'^```json\s*|\s*```$', '', result_text, flags=re.MULTILINE)
        
        plan_data = json.loads(result_text)
        
        # Calculate real driving directions if ORS is available
        if ors_client:
            coords = []
            
            # 1. Start from Source if we have it
            if source_lat and source_lon:
                coords.append([source_lon, source_lat])
                # Also ensure plan_data has these for the frontend markers
                plan_data['source_lat'] = source_lat
                plan_data['source_lon'] = source_lon
                plan_data['source_name'] = source
            
            # 2. Add first hotel as base if available
            if plan_data.get('hotels') and len(plan_data['hotels']) > 0:
                h = plan_data['hotels'][0]
                if h.get('lon') and h.get('lat'):
                    coords.append([h['lon'], h['lat']])
            
            # 3. Add itinerary activities in sequence
            if plan_data.get('itinerary'):
                for day in plan_data['itinerary']:
                    if day.get('activities'):
                        for act in day['activities']:
                            if isinstance(act, dict) and act.get('lon') and act.get('lat'):
                                coords.append([act['lon'], act['lat']])
            
            # Filter nulls just in case
            valid_coords = [[float(lon), float(lat)] for lon, lat in coords if lon is not None and lat is not None]
            
            if len(valid_coords) > 1:
                try:
                    # Prevent exceeding max waypoints
                    route = ors_client.directions(coordinates=valid_coords[:50], profile='driving-car', format='geojson')
                    plan_data['route_geometry'] = route
                    # Extract distance in km
                    if route.get('features') and len(route['features']) > 0:
                        props = route['features'][0].get('properties', {})
                        summary = props.get('summary', {})
                        if summary.get('distance'):
                            plan_data['total_distance_km'] = round(summary['distance'] / 1000, 2)
                except Exception as e:
                    logging.error(f"OpenRouteService Error: {e}")
                    
        if source:
            train = get_train_route(source, destination)
            if train:
                plan_data['train_details'] = train

        return jsonify(plan_data)
        
    except Exception as e:
        logging.error(f"Error parsing AI response: {e}")
        return jsonify({"error": "AI response was not valid JSON: " + result_text[:100]}), 500

@app.route('/api/weather', methods=['GET'])
def get_weather():
    city = request.args.get('city')
    if not city or not WEATHER_API_KEY:
        return jsonify({"error": "City missing or Weather API not configured"}), 400
    
    try:
        # Get coordinates for the city
        geocode_url = f"http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=1&appid={WEATHER_API_KEY}"
        geocode_response = requests.get(geocode_url).json()
        
        if not geocode_response:
            return jsonify({"error": "City not found"}), 404
            
        lat = geocode_response[0]['lat']
        lon = geocode_response[0]['lon']
        
        # Get weather forecast
        weather_url = f"http://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&units=metric&appid={WEATHER_API_KEY}"
        weather_response = requests.get(weather_url).json()
        
        # Just return the first few days of daily forecasts (picking one time slot per day)
        forecasts = []
        seen_dates = set()
        
        for item in weather_response.get('list', []):
            date = item['dt_txt'].split(' ')[0] # YYYY-MM-DD
            if date not in seen_dates:
                seen_dates.add(date)
                forecasts.append({
                    "date": date,
                    "temp": item['main']['temp'],
                    "description": item['weather'][0]['description'],
                    "icon": item['weather'][0]['icon']
                })
                
        return jsonify({"forecast": forecasts[:5]})
        
    except Exception as e:
        logging.error(f"Error fetching weather: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/chat', methods=['POST'])
def chat_assistant():
    data = request.json
    messages = data.get('messages', [])
    
    if not messages:
        return jsonify({"error": "Missing messages"}), 400
        
    # Prepend system prompt
    system_prompt = {"role": "system", "content": "You are a professional travel assistant specialized in planning trips for Indian tourists. Focus on high-quality, reliable information in India or abroad, using INR currency."}
    full_messages = [system_prompt] + messages
    
    reply = get_ai_response(full_messages, temp=0.7)
    
    if reply:
        return jsonify({"reply": reply})
    else:
        return jsonify({"error": "AI could not generate a reply"}), 500

@app.route('/api/parse_voice_intent', methods=['POST'])
def parse_voice_intent():
    data = request.json
    text = data.get('text', '')
    
    if not text:
        return jsonify({"error": "No text provided"}), 400
        
    messages = [
        {"role": "system", "content": "You are an intelligent NLP parser. The user is speaking naturally to an AI trip planner. Extract their desired travel parameters. Return ONLY raw JSON format (no markdown, no backticks). Keys required: 'destination' (string, extract the city/place they want to visit), 'source' (string, their starting location or empty string if not mentioned), 'budget' (integer, extract numerical budget, default to 50000 if not stated), 'days' (integer, number of days, default to 3 if not stated). The input may be in Kannada, English, or a mix. You must extract the parameters correctly, but return the JSON string values (like destination) strictly as English names (e.g., if input says 'ನಾನು ಗೋವಾ ಹೋಗಬೇಕು', destination is 'Goa')."},
        {"role": "user", "content": f"Extract details from this spoken text: '{text}'"}
    ]
    
    reply = get_ai_response(messages, temp=0.1)
    if not reply:
        return jsonify({"error": "AI could not generate a reply"}), 500
        
    try:
        if reply.startswith('```'):
            import re
            reply = re.sub(r'^```json\s*|\s*```$', '', reply, flags=re.MULTILINE)
        intent_data = json.loads(reply)
        return jsonify(intent_data)
    except Exception as e:
        logging.error(f"Error parsing voice intent JSON: {e}")
        return jsonify({"error": "Invalid format returned by AI"}), 500

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
